[1,"- The project is out-of-sync -- use `\u001B]8;;x-r-run:renv::status()\u0007renv::status()\u001B]8;;\u0007` for details.\r\n"]
[1,"\u001B[31merror\u001B[39m\u001B[31m: Uncaught (in promise) YAMLException: unidentified alias \"*Note.**\" (D:\\Github\\TranQuocHoang_IM25_Newsletter\\TranQuocHoang_IM25_Newsletter\\TranQuocHoang_IM25_Newsletter.qmd, 63:13)\r\n"]
[1,"62: #| fig-cap: \"Environmental sources and human exposure of MNPs.\"\r\n"]
[1,"63: #| **Note.** Reprinted from [@maNeurotoxicityMicroNanoplastics2025].\"\r\n"]
[1,"               ~~\r\n"]
[1,"64: knitr::include_graphics(\"images/entry-routes.jpeg\")\r\n"]
[1,"    return new exception(message, mark);\r\n"]
[1,"           ^\r\n"]
[1,"    at generateError (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:13996:12)\r\n"]
[1,"    at throwError (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:13999:11)\r\n"]
[1,"    at readAlias (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:14786:9)\r\n"]
[1,"    at composeNode (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:14847:28)\r\n"]
[1,"    at readBlockMapping (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:14609:18)\r\n"]
[1,"    at composeNode (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:14842:84)\r\n"]
[1,"    at readDocument (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:14972:5)\r\n"]
[1,"    at loadDocuments (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:15014:9)\r\n"]
[1,"    at load$1 (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:15032:21)\r\n"]
[1,"    at buildJsYamlAnnotation (file:///D:/Program Files/RStudio/resources/app/bin/quarto/bin/quarto.js:15829:5)\r\n"]
[1,"\u001B[39m"]
[1,"\u001B[1m\u001B[33mError\u001B[39m in `quarto::quarto_render()`:\u001B[22m\r\n"]
[1,"\u001B[1m\u001B[22m\u001B[33m!\u001B[39m Error running quarto CLI from R.\r\n"]
[1,"\u001B[1mCaused by error in `quarto::quarto_render()`:\u001B[22m\r\n"]
[1,"\u001B[1m\u001B[22m\u001B[31m✖\u001B[39m Error returned by quarto CLI.\r\n"]
[1,"  -----------------------------\r\n"]
[1,"  error: Uncaught (in promise) YAMLException: unidentified alias \"*Note.**\"\r\n"]
[1,"  (D:\\Github\\TranQuocHoang_IM25_Newsletter\\TranQuocHoang_IM25_Newsletter\\TranQuocHoang_IM25_Newsletter.qmd,\r\n"]
[1,"  63:13)\r\n"]
[1,"  62: #| fig-cap: \"Environmental sources and human exposure of MNPs.\"\r\n"]
[1,"  63: #| **Note.** Reprinted from [@maNeurotoxicityMicroNanoplastics2025].\"\r\n"]
[1,"  ~~\r\n"]
[1,"  64: knitr::include_graphics(\"images/entry-routes.jpeg\")\r\n"]
[1,"  return new exception(message, mark);\r\n"]
[1,"  ^\r\n"]
[1,"  at generateError (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:13996:12)\r\n"]
[1,"  at throwError (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:13999:11)\r\n"]
[1,"  at readAlias (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:14786:9)\r\n"]
[1,"  at composeNode (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:14847:28)\r\n"]
[1,"  at readBlockMapping (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:14609:18)\r\n"]
[1,"  at composeNode (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:14842:84)\r\n"]
[1,"  at readDocument (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:14972:5)\r\n"]
[1,"  at loadDocuments (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:15014:9)\r\n"]
[1,"  at load$1 (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:15032:21)\r\n"]
[1,"  at buildJsYamlAnnotation (file:///D:/Program\r\n"]
[1,"  Files/RStudio/resources/app/bin/quarto/bin/quarto.js:15829:5)\r\n"]
[1,"  \r\n"]
[1,"\u001B[1mCaused by error:\u001B[22m\r\n"]
[1,"\u001B[33m!\u001B[39m System command 'quarto.exe' failed\r\n"]
[1,"Backtrace:\r\n"]
[1,"\u001B[90m     \u001B[39m▆\r\n"]
[1,"\u001B[90m  1. \u001B[39m├─.rs.sourceWithProgress(...)\r\n"]
[1,"\u001B[90m  2. \u001B[39m│ └─\u001B[1mbase\u001B[22m::eval(statements[[idx]], envir = globalenv())\r\n"]
[1,"\u001B[90m  3. \u001B[39m│   └─base::eval(statements[[idx]], envir = globalenv())\r\n"]
[1,"\u001B[90m  4. \u001B[39m├─\u001B[1m\u001B[94mquarto::quarto_render(\u001B[39m\u001B[22m\u001B[1m\u001B[94m)\u001B[39m\u001B[22m\r\n"]
[1,"\u001B[90m  5. \u001B[39m│ └─quarto:::quarto_run(args, echo = TRUE, quarto_bin = quarto_bin)\r\n"]
[1,"\u001B[90m  6. \u001B[39m│   ├─\u001B[1mbase\u001B[22m::withCallingHandlers(...)\r\n"]
[1,"\u001B[90m  7. \u001B[39m│   └─\u001B[1mprocessx\u001B[22m::run(...)\r\n"]
[1,"\u001B[90m  8. \u001B[39m│     └─throw(...)\r\n"]
[1,"\u001B[90m  9. \u001B[39m│       └─\u001B[1mbase\u001B[22m::signalCondition(cond)\r\n"]
[1,"\u001B[90m 10. \u001B[39m└─\u001B[1mquarto\u001B[22m (local) `<fn>`(`<S3: system_command_status_error>`)\r\n"]
[1,"\u001B[90m 11. \u001B[39m  └─quarto:::wrap_quarto_error(e, args, .call = .call)\r\n"]
[1,"\u001B[90m 12. \u001B[39m    └─\u001B[1mcli\u001B[22m::cli_abort(msg, call = .call, parent = cnd, )\r\n"]
[1,"\u001B[90m 13. \u001B[39m      └─\u001B[1mrlang\u001B[22m::abort(...)\r\n"]
[2,"Execution halted\r\n"]
